# Site information
site_name: HESTIA Documentation
site_url: https://sitename.example
site_author: Ioanna Kechlimpari
site_description: HESTIA Documentation

# Copyright
copyright: Copyright &copy; 2025 TEXTaiLES

# Config
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
 # logo: assets/thoth-logo.png #portal-logo
 # favicon: assets/thoth-logo.png #portal-logo

# Extra
extra:
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/TEXTaiLES

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

# Page
nav:
  - Portal:
    - General Information: 
      - License: portal/generalInformation/licenses.md
    - Deployment: 
      - Public link: portal/deployment/link.md
    - Manual:
      - Home: portal/manual/home.md
      - Collections: portal/manual/collections.md
      - Tools: portal/manual/toolbox.md
    - Artifact Accessibility:
      - Admin User: portal/accessibility/adminUser.md
      - Public User: portal/accessibility/publicUser.md
    - Integration:
      - Token-Based Authentication: portal/integration/directus-login.md
      - Cookie-Based Authentication: portal/integration/directus-cookie.md